version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    env_file:
      - client/.env
    depends_on:
      - server
    networks:
      - server_network
    ports:
      - '5137:5137'
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env
    networks:
      - server_network
    ports:
      - '3000:3000'
networks:
  server_network: 
    name: server_network
